// <auto-generated />
using System;
using CommunityLibrary.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityLibrary.MVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CommunityLibrary.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ubaldo Hayes",
                            Category = "Fiction",
                            IsAvailable = true,
                            Isbn = "9856348947658",
                            Title = "Fantastic Fresh Gloves"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Laura Little",
                            Category = "Non-Fiction",
                            IsAvailable = true,
                            Isbn = "1628238745952",
                            Title = "Ergonomic Wooden Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lisandro Spinka",
                            Category = "Technology",
                            IsAvailable = true,
                            Isbn = "5195517737848",
                            Title = "Intelligent Plastic Chicken"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Clementina Hackett",
                            Category = "Non-Fiction",
                            IsAvailable = true,
                            Isbn = "1051759309547",
                            Title = "Gorgeous Soft Pants"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Danyka Kilback",
                            Category = "Mystery",
                            IsAvailable = true,
                            Isbn = "6610050180665",
                            Title = "Fantastic Granite Ball"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Karen MacGyver",
                            Category = "Technology",
                            IsAvailable = false,
                            Isbn = "3433511818548",
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mohammad McDermott",
                            Category = "History",
                            IsAvailable = false,
                            Isbn = "1099066873269",
                            Title = "Generic Steel Pants"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Virgil Schneider",
                            Category = "Biography",
                            IsAvailable = false,
                            Isbn = "0209823253000",
                            Title = "Intelligent Fresh Salad"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Santino Koepp",
                            Category = "Biography",
                            IsAvailable = false,
                            Isbn = "5337674765337",
                            Title = "Fantastic Wooden Table"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Elza Koch",
                            Category = "History",
                            IsAvailable = false,
                            Isbn = "5117580276789",
                            Title = "Ergonomic Metal Bike"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Eliza McKenzie",
                            Category = "History",
                            IsAvailable = false,
                            Isbn = "4262515882793",
                            Title = "Small Plastic Shirt"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Salma Pagac",
                            Category = "Fiction",
                            IsAvailable = false,
                            Isbn = "2885739797135",
                            Title = "Incredible Steel Chicken"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Randal Barton",
                            Category = "Fantasy",
                            IsAvailable = false,
                            Isbn = "8260179857344",
                            Title = "Intelligent Soft Car"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Brannon Kessler",
                            Category = "Non-Fiction",
                            IsAvailable = false,
                            Isbn = "7852381864251",
                            Title = "Handmade Wooden Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Roy Marks",
                            Category = "Non-Fiction",
                            IsAvailable = false,
                            Isbn = "0270588145930",
                            Title = "Incredible Granite Chair"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Easter Waters",
                            Category = "Technology",
                            IsAvailable = true,
                            Isbn = "4698930469590",
                            Title = "Fantastic Steel Pants"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Leslie VonRueden",
                            Category = "History",
                            IsAvailable = true,
                            Isbn = "7636313582280",
                            Title = "Licensed Fresh Soap"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Kale Fay",
                            Category = "History",
                            IsAvailable = true,
                            Isbn = "6124002954629",
                            Title = "Refined Steel Soap"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Luna Medhurst",
                            Category = "Technology",
                            IsAvailable = true,
                            Isbn = "6827435727470",
                            Title = "Generic Soft Keyboard"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Wilson Jones",
                            Category = "Fiction",
                            IsAvailable = true,
                            Isbn = "6262346885763",
                            Title = "Gorgeous Concrete Tuna"
                        });
                });

            modelBuilder.Entity("CommunityLibrary.Domain.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DueDate = new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnedDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            DueDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnedDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            DueDate = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            ReturnedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            DueDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnedDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            DueDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            ReturnedDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            DueDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            DueDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            DueDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            DueDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            DueDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            DueDate = new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            DueDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            DueDate = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            DueDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            DueDate = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5
                        });
                });

            modelBuilder.Entity("CommunityLibrary.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Jed_Robel@yahoo.com",
                            FullName = "Anais Stanton",
                            Phone = "07040 439440"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Salvador_Gerhold61@yahoo.com",
                            FullName = "Maia Herman",
                            Phone = "07156 889305"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Graham_Waters48@hotmail.com",
                            FullName = "Eunice Gottlieb",
                            Phone = "07178 501486"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Delphia24@gmail.com",
                            FullName = "Ardith Schinner",
                            Phone = "07032 811563"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Kylee_Ondricka43@gmail.com",
                            FullName = "Rae Nikolaus",
                            Phone = "07301 701429"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Tina9@yahoo.com",
                            FullName = "Constance Smith",
                            Phone = "07536 403021"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Cordell34@yahoo.com",
                            FullName = "Chris Gibson",
                            Phone = "07178 004928"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Mathew.Bode@hotmail.com",
                            FullName = "Lawrence Davis",
                            Phone = "07319 211309"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Rose70@hotmail.com",
                            FullName = "Sage Murphy",
                            Phone = "07144 241014"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Camryn.Crooks@yahoo.com",
                            FullName = "Haylie Osinski",
                            Phone = "07770 027203"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CommunityLibrary.Domain.Loan", b =>
                {
                    b.HasOne("CommunityLibrary.Domain.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunityLibrary.Domain.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityLibrary.Domain.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("CommunityLibrary.Domain.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
